### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by MiSikora** [szymonkozak/tempomat#37]
Configuration handling needs some love. We should standardize it so it can be easily editable and extensible. One of the propositions we discussed was to use a YAML file.

```yaml
version: 1
selectedAccount: default
accounts:
  default:
    jiraName: somename
    accountId: 123
    token: 345
    config:
      settings:
        someFlag: true
        defaultRemainingEstimate: 1h
      aliases:
        sm: abc-123
        daily: abc-123
        lunch: abc-321
      attributes:
        _EXTERNALREF_: foo
        _COLOR_: green
  jake:
    jiraName: somename
    accountId: 123
    token: 345
    config:
      settings:
        defaultRemainingEstimate: 1h
      aliases: []
      attributes:
        _EXTERNALREF_: foo
        _COLOR_: green
config:
  settings:
    defaultRemainingEstimate: 0h
  aliases:
    sm: abc-123
    daily: abc-123
    lunch: abc-321
  attributes:
    _EXTERNALREF_: foo
    _COLOR_: green
```

While it would serve its purpose I'm not the biggest fan of the YAML format. I'd like us to consider TOML or HOCON which in my opinion have better syntax.

**Comment by szymonkozak** [comment]
I modified some keys and my proposition is something like that:
```yaml
version: 2
selectedAccount: default
accounts:
  default:
    jiraName: somename
    accountId: 123
    token: 345
    accountConfig:
      settings:
        someFlag: true
        defaultRemainingEstimate: 1h
      aliases:
        sm: abc-123
        daily: abc-123
        lunch: abc-321
      attributes:
        _EXTERNALREF_: foo
        _COLOR_: green
  jake:
    jiraName: somename
    accountId: 123
    token: 345
    accountConfig:
      settings:
        defaultRemainingEstimate: 1h
      aliases: []
      attributes:
        _EXTERNALREF_: foo
        _COLOR_: green
globalConfig:
  settings:
    defaultRemainingEstimate: 0h
  aliases:
    sm: abc-123
    daily: abc-123
    lunch: abc-321
  attributes:
    _EXTERNALREF_: foo
    _COLOR_: green
```
